completions_kwargs:
  batch_size: 900
  do_sample: true
  max_new_tokens: 4096
  model_kwargs:
    torch_dtype: bfloat16
  tokenizer_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
  stop_token_ids:
    - 128001
    - 128009
  temperature: 0.9
  top_p: 1.0
prompt_template: eval/alpacaeval/templates/llama3.txt